version: '3.1'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: php-my-app
    restart: unless-stopped
    tty: true
    environment:
      - TERM=xterm-256color
      - SERVICE_NAME=php-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/vendor
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini      
    networks:
      - app-network

  #Nginx Service For Development Only
  webserver:
    image: nginx:alpine
    container_name: webserver-my-app
    restart: unless-stopped
    environment:
      - TERM=xterm-256color
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/certs/:/etc/nginx/certs/
    networks:
      - app-network


  #Node Service For Development Only
  node:
    image: node:10
    container_name: node-my-app
    restart: unless-stopped
    tty: true
    environment:
      - TERM=xterm-256color
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    ports: 
      - "9056:9056"
    command: "tail -f /dev/null"
    networks:
      - app-network

  

#Docker Networks
networks:
  app-network:
    driver: bridge
